spring.application.name=geodais
#spring.datasource.url=jdbc:oracle:thin:@192.168.1.12:1521:DEVIDA
spring.datasource.url=jdbc:oracle:thin:@192.168.1.237:1521:DEVIDA
spring.datasource.username=geodais
spring.datasource.password=desarrollo
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración de JPA / Hibernate para Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Contexto y Seguridad básica
server.servlet.context-path=/geodais
spring.security.user.name=devida
spring.security.user.password=geodais-dev